name: MarkdownLint
on:
  pull_request:
    paths:
      - 'markdownlint/**'
      - '!markdownlint/docs/**'

jobs:
  test_custom_rules:
    name: Test custom Markdownlint rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test
